name:           "Simple Share Popups"
description:    A small collection of methods for adding share buttons that don't rely on JavaScript or any authorization stuff.
image:          image.jpg
url:            https://paulmolluzzo.github.io/simple_share_popups/
encodedUrl:     https%3A%2F%2Fpaulmolluzzo.github.io%2Fsimple_share_popups%2F
twitter:        paulmolluzzo

markdown:      redcarpet